version: "3.8"

services:
  celery-beat:
    env_file:
      - .env
    image: policy-insight-celery-beat
    container_name: policy-insight-celery-beat
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    volumes:
      - ./requirements/backend:/code
    command: celery -A app.tasks.celery_app beat --loglevel=info
    depends_on:
      - rabbitmq
      - postgresql
      - celery
    networks:
      - app_network
    restart: unless-stopped
